FROM node:22-alpine

WORKDIR /app

COPY package*.json tsconfig.json ./

RUN npm install

COPY . .

# Build Next.js app
RUN npm run build

# Expose Next.js default port
EXPOSE 3000

# Run Next.js
CMD ["npm", "start"]
